version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: payment_db
    ports:
      - "5432:5432"
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: always

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    environment:
      - DB_DSN=postgres://user:password@postgres:5432/payment_db?sslmode=disable
      - REDIS_ADDR=redis:6379
      - PAYMENT_GRPC_ADDR=payment-service:50052
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    restart: always

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    environment:
      - DB_DSN=postgres://user:password@postgres:5432/payment_db?sslmode=disable
      - GRPC_PORT=50052
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    ports:
      - "50052:50052"
    depends_on:
      - postgres
      - rabbitmq
    restart: always

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - REDIS_ADDR=redis:6379
      - PROVIDER_MODE=SIMULATED
    depends_on:
      - rabbitmq
      - redis
    restart: always


volumes:
      postgres_data: